language: python
env:
  - BOTO_CONFIG=/dev/null
python:
  - "2.7"
  - "3.6"
before_install:
  # install and run latest DynamoDB Local
  - mkdir /tmp/dynamodb_local
  - wget -O - https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz | tar xz --directory /tmp/dynamodb_local
  - java -Djava.library.path=/tmp/dynamodb_local/DynamoDBLocal_lib -jar /tmp/dynamodb_local/DynamoDBLocal.jar -sharedDb -inMemory &
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - flake8 --ignore=E501
  - mkdir dump && cp -a test/testTable dump
  # test basic restore and backup
  - python dynamodump.py -m restore -r local -s testTable -d testRestoredTable --host localhost --port 8000 --accessKey a --secretKey a
  - python dynamodump.py -m backup -r local -s testRestoredTable --host localhost --port 8000 --accessKey a --secretKey a
  - python test/test.py
  # test wildcard restore and backup
  - python dynamodump.py -m restore -r local -s "*" --host localhost --port 8000 --accessKey a --secretKey a
  - rm -rf dump/test*
  - python dynamodump.py -m backup -r local -s "*" --host localhost --port 8000 --accessKey a --secretKey a
  - python test/test.py
  # test prefixed wildcard restore and backup
  - python dynamodump.py -m restore -r local -s "test*" --host localhost --port 8000 --accessKey a --secretKey a --prefixSeparator ""
  - rm -rf dump/test*
  - python dynamodump.py -m backup -r local -s "test*" --host localhost --port 8000 --accessKey a --secretKey a --prefixSeparator ""
  - python test/test.py
matrix:
    fast_finish: true
